export const products = [
  {
    title: "Courrier X Logistics App",
    image: "./images/product-1.jpg",
    description: "Reliable  and user-friendly interface",
    category: "Transportation",
    url: "",
  },
  {
    title: "Order X Food ordering & delivery APP",
    image: "./images/product-2.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Food",
    url: "",
  },
  {
    title: "OrderX Restaurant Management & POS App",
    image: "./images/product-3.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Food",
    url: "",
  },
  {
    title: "Order X Grocery delivery App",
    image: "./images/product-4.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Food",
    url: "",
  },
  {
    title: "Order X Pharmacy delivery App",
    image: "./images/product-5.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Health & Lifestyle",
    url: "",
  },
  {
    title: "Order X Gas delivery App",
    image: "./images/product-6.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Transportation",
    url: "",
  },
  {
    title: "Order X Laundry delivery App",
    image: "./images/product-7.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Transportation",
    url: "",
  },
  {
    title: "Order X Online Store & Delivery App",
    image: "./images/product-8.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Transportation",
    url: "",
  },
  {
    title: "Order X Heatlhcare & Fitness consultation App",
    image: "./images/product-9.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Health & Lifestyle",
    url: "",
  },
  {
    title: "HotelX- Hotel Management and POS Solution",
    image: "./images/product-10.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Health & Lifestyle",
    url: "",
  },
  {
    title: "Uberlike Ride hailling App",
    image: "./images/product-11.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Transportation",
    url: "",
  },
  {
    title: "Uberlike Taxi hailing App",
    image: "./images/product-12.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Transportation",
    url: "",
  },
  {
    title: "CryptoX Bitcoin Mining App",
    image: "./images/product-13.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Crypto",
    url: "",
  },
  {
    title: "CryptoX Trading Investment App",
    image: "./images/product-14.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Crypto",
    url: "",
  },
  {
    title: "PayX - Loan & Investment App",
    image: "./images/product-15.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Fintech",
    url: "",
  },
  {
    title: "School 360 LMS solution",
    image: "./images/product-16.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Education",
    url: "",
  },
  {
    title: "School 360 SMS solution",
    image: "./images/product-17.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Education",
    url: "",
  },
  {
    title: "TotalX CRM",
    image: "./images/product-18.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Fintech",
    url: "",
  },
  {
    title: "TotalX ERP",
    image: "./images/product-19.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Fintech",
    url: "",
  },
  {
    title: "GrowthX Business suite App",
    image: "./images/product-20.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Fintech",
    url: "",
  },
  {
    title: "TotalX Accounting & Book keeping App",
    image: "./images/product-21.jpg",
    description: "Hassle-free food ordering and delivery",
    category: "Fintech",
    url: "",
  },
];

export const prods = [
  {
    title: "School 360",
    description: "EDUCATION",
    image: "./images/product-16.jpg",
    url: "",
  },
  {
    title: "Order X Food ordering & delivery APP",
    description: "FOOD",
    image: "./images/food.jpg",
    url: "",
  },
  {
    title: "Courrier X Logistics App",
    image: "./images/courrier.jpg",
    description: "TRANSPORTATION",
    url: ""
  },
  {
    title: "Order X Grocery delivery App",
    image: "./images/grocery.jpg",
    description: "FOOD",
    url: "",
  },
  {
    title: "Order X Pharmacy delivery App",
    image: "./images/pharmacy.jpg",
    description: "HEALTH",
    url: "",
  },
  {
    title: "Order X Laundry delivery App",
    image: "./images/product-7.jpg",
    description: "BUSINESS",
    url: "",
  },
  {
    title: "Order X Online Store & Delivery App",
    image: "./images/online-store.jpg",
    description: "BUSINESS",
    url: "",
  },
  {
    title: "Order X Heatlhcare & Fitness consultation App",
    image: "./images/fitness.jpg",
    description: "HEALTH",
    url: "",
  },
  {
    title: "HotelX- Hotel Management and POS Solution",
    image: "./images/hotel.jpg",
    description: "HOUSING",
    url: "",
  },
  {
    title: "Uberlike Ride hailling App",
    image: "./images/taxi.jpg",
    description: "TRANSPORTATION",
    url: "",
  },
  {
    title: "CryptoX Bitcoin Mining App",
    image: "./images/product-13.jpg",
    description: "TRADING",
    url: "",
  },
  {
    title: "CryptoX Trading Investment App",
    image: "./images/product-14.jpg",
    description: "TRADING",
    url: "",
  },
  {
    title: "PayX - Loan & Investment App",
    image: "./images/loan.jpg",
    description: "FINANCE",
    url: "",
  },
  {
    title: "School 360 LMS solution",
    image: "./images/lms.jpg",
    description: "EDUCATION",
    url: "",
  },
  {
    title: "School 360 SMS solution",
    image: "./images/sms.jpg",
    description: "EDUCATION",
    url: "",
  },
  {
    title: "TotalX CRM",
    image: "./images/crm.jpg",
    description: "MANAGEMENT",
    url: "",
  },
  {
    title: "TotalX ERP",
    image: "./images/erp.jpg",
    description: "MANAGEMENT",
    url: "",
  },
  {
    title: "TotalX Accounting & Book keeping App",
    image: "./images/accounting.jpg",
    description: "MANAGEMENT",
    url: "",
  },
];

export const partnerImages = [
  {
    img_url: "./images/partner-1.png",
  },
  {
    img_url: "./images/partner-2.png",
  },
  {
    img_url: "./images/partner-3.png",
  },
  {
    img_url: "./images/partner-4.png",
  },
  {
    img_url: "./images/partner-5.png",
  },
];